CREATE TABLE LocationZone(id INTEGER PRIMARY KEY AUTOINCREMENT, descrition TEXT NOT NULL, latitude REAL NOT NULL, longitude REAL NOT NULL, radius REAL NOT NULL, emailNotification TEXT, phoneNotification TEXT, ativo TEXT NOT NULL);
CREATE TABLE Questions(id INTEGER PRIMARY KEY AUTOINCREMENT, question TEXT NOT NULL);
CREATE TABLE Answers(id INTEGER PRIMARY KEY AUTOINCREMENT, questionID INTEGER NOT NULL, answer TEXT NOT NULL, userId TEXT NOT NULL, dataInclusao TEXT NOT NULL);
CREATE TABLE User(id INTEGER PRIMARY KEY, nome INTEGER NOT NULL, tipoUser TEXT NOT NULL);